### ISSUE TITLE
Loop Gradient Rings - Questions

### ISSUE THREAD

**Issue by WanaGo** [jonfawcett/Nightscout-Tasker-Tizen-Watchface-Integration#3]
Hi.
Loving what you are doing here. Not wanting to steal what you have done at all, just learning how these things work.
In your Loop Gradient Rings watch file, its all in mg/dL I assume. I see a calculation for the BG value which goes around the bottom right side of the watch.  >300 and -40, or > 100 and 72 etc etc. Can you help me understand this? What does the 1.78 and 0.91 relate to in that formula? And the 72?
Do you have plans to make this for non Loop situations, and for mmol/L instead of mg/dL ?
Respect.
Thanks

**Comment by SJoWie80** [comment]
i use `string.format("%.1f",{tloopbg} / 18)` for mmol/l calculation

**Comment by WanaGo** [comment]
More specifically asking about this

({tloopbg}>300) and -40 or ({tloopbg} > 100) and 72-(({tloopbg}-100)/1.78) or 72+((100-{tloopbg})/.91)

**Comment by jonfawcett** [comment]
We are mg/dl, so dexcom reads 40-400. I prefer to put my daughter's target of 100 at the center of the arc. This gives it more fine tuned movement for lows on the arc. She is also rarely over 300, so I squash 300-400 down to the maximum. So here is what it all does... 
- the >300 sets everything higher than 300 at max rotation of -40 
- >100 runs the math for BG above target. 72 is the center of rotation and I subtract 100 since 100 bg is already the center. The 1.78 is the ratio between degrees from center to max and BG from 100-300
- the else at the end does the same thing except for values under 100

I don't have plans for mmol since we don't use it. But one reason I put this on github was so anyone else can contribute with this types of things. I don't think the tasks will need changes, just the watch face matches. For non-loop there is already a task that removes all of that and then just edit the watch faces to remove the non-loop items. Some of these you can convert to things like weather, steps, etc very easily. And anyone can send a PR for new or edited faces too.

**Comment by WanaGo** [comment]
Thanks very much, very clever

**Comment by Sergio-83** [comment]
hi man, tell me please how i can change displayed value glucose mg to mmol? 

sorry for my english, i am from russia
